spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange: user.exchange
    queue: user.queue
    routingkey: user.routingkey

  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=UTC
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true

server:
  port: 8081   # <-- Port libre pour éviter conflit avec 8080
